# Release: https://github.com/scrtlabs/fetch-web-demo/releases/tag/v0.0.8
# Workflow URL: https://github.com/scrtlabs/fetch-web-demo/actions/runs/16220142716
# Commit: https://github.com/scrtlabs/fetch-web-demo/commit/3d5448ea8f09ddc5dcd840e4e9390d6a6f5ea28c
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/scrtlabs/fetch-web-demo@sha256:5bb278c6c4ad633fb0c1e5f76da5993391e2103f43aaed9559b0f3a6b40e0bc6
    ports:
      - '8080:80'
