version: '3.8'

services:
  medical-diagnostics-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medical-diagnostics-platform
    ports:
      - "8080:80"
    volumes:
      # Mount logs for debugging (optional)
      - ./logs:/var/log/nginx
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.medical-app.rule=Host(`medical-diagnostics.local`)"
      - "traefik.http.services.medical-app.loadbalancer.server.port=80"

  # Optional: Add a reverse proxy for SSL/domain routing
  # Uncomment if you want to use Traefik for routing
  # traefik:
  #   image: traefik:v2.10
  #   container_name: traefik
  #   command:
  #     - "--api.insecure=true"
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=false"
  #     - "--entrypoints.web.address=:80"
  #   ports:
  #     - "80:80"
  #     - "8081:8080"  # Traefik dashboard
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #   restart: unless-stopped

networks:
  default:
    name: medical-diagnostics-network